### ISSUE TITLE
Change Player Heads API & Add cache

### ISSUE THREAD

**Issue by lucas2107** [mathhulk/advancedban-panel#37]
Change Heads & Skulls API to https://crafatar.com ( faster )
#38 

Add a cache for heads & skulls (10s to load..)

**Comment by lucas2107** [comment]
#38

**Comment by Legoman99573** [comment]
Problem is it requires UUID only now. Plus images are now async loaded.

**Comment by mathhulk** [comment]
The option for skull images has been removed, as the option was unstable. I might add the option back in a future update when I can add caching in a proper manner.
