### ISSUE TITLE
UUID not Correct

### ISSUE THREAD

**Issue by ICEconchy** [mathhulk/advancedban-panel#45]
Hello, I can't seem to get UUID working in the panel. It seems that it displays 1 uuid for everyone but the one listed in the database is different.

The uuid that always appears is: 8667ba71b85a4004af54457a9734eed7

**Comment by mathhulk** [comment]
The UUIDs from the database were inconsistent and thus I used an API to gather them from usernames. However, this proved to increase load times and was used just for skull images, which have been removed in the current release.
