### ISSUE TITLE
Order change

### ISSUE THREAD

**Issue by winnipeg21** [mathhulk/advancedban-panel#47]
Currently the order is;
Name  Reason  Operator  Date  End  Type  Status
(That's for the main page)

A new order should follow examples from popular servers and panels of different plugins. The new order should be;
Name  Operator  Reason  Date  End  Type  Status.

Another option could be a customized config that would allow you to change the order and what's displayed depending on what the user wants.

**Comment by winnipeg21** [comment]
Follow the same type of design for the Liteban material design.

**Comment by mathhulk** [comment]
I am going to keep the order the same for now. I don't see a reason to change the order, as placing the reason next to the user seems to be the most effective layout.
