### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by winnipeg21** [mathhulk/advancedban-panel#48]
Currently, the main design is focused on one page with different filters to sort out mutes, bans, ip bans, etc... A new design could use 5 pages. A homepage which would display the custom header and description set in a could or by editing the files. Then 4 different pages for Bans (temp, ip and bans), Mutes, Warnings and kicks. Each one the same and have the ability to change the names. Instead of having Punished By or Operator, have Kicked By or Muted By. And if you want have another page with all punishments. And keep the search bar on each page or in the nav bar.

**Comment by winnipeg21** [comment]
Follow the same type of design for the Liteban material design.

**Comment by mathhulk** [comment]
I think I am going to keep the design the same for now. Feel free to use custom themes to change the layout and style of the panel.
