### ISSUE TITLE
Expire date is Jan 1970 when ban is permanent. 

### ISSUE THREAD

**Issue by Puggetty** [mathhulk/advancedban-panel#52]
Hello
Whenever I set the ban to permanent it shows up on the webpage as expiring on January 1st 1970, I have attached a picture.
Any solutions to make it say "never" or "permanent"?
Thanks
![bans](https://user-images.githubusercontent.com/16494234/45268543-bffcf700-b475-11e8-8ac6-1b28c531c09e.PNG)

**Comment by mathhulk** [comment]
Are you sure you are using the latest archive from GitHub? I made some fixes after the last update on SpigotMC so you should make sure you download again. The expire field should show “N/A” when a punishment does not expire.

**Comment by Puggetty** [comment]
All fixed by downloading new panel, cheers bud :)

**Comment by mathhulk** [comment]
Glad the updates fixed your issues. Thanks for reporting.
