### ISSUE TITLE
Error while loading Page

### ISSUE THREAD

**Issue by xXSchrandXx** [mathhulk/advancedban-panel#55]
Hi, I am getting this Error:
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
[Link to my page](http://ban.ragebears.de)

I don't know why. Everything is correctly set up.

Do you have a guess what Chrome can't load?

**Comment by falceso** [comment]
Hey there @xXSchrandXx,

Please answer the following two questions so we can get a slightly deeper scope into the error. 
Do you have php errors enabled?
Are your database information correct?

**Comment by xXSchrandXx** [comment]
Sry, I am still waiting for the owner to correct the log path. But I can say that the database is correct.

**Comment by winnipeg21** [comment]
Make sure your database it set up correctly. If your webserver is hosted on the same machine as your MySQL and server use localhost. If your MySQL and server are on one machine but your webserver is on a different machine make sure your MySQL has remote access (contact provider if need be). Another issue could be not having the proper php version or your site is messed up. I suggest a reinstall if need be.

**Comment by xXSchrandXx** [comment]
Error: 
`[Mon Dec 03 20:08:58.548355 2018] [:error] [pid ####] [client ***] PHP Catchable fatal error:  Argument 1 passed to AdvancedBan::initialize() must be an instance of string, string given, called in /var/www/ban/index.php on line 23 and defined in /var/www/ban/AdvancedBan/AdvancedBan.class.php on line 30
`
SQL is localand host is local

**Comment by xXSchrandXx** [comment]
> I suggest a reinstall if need be.

Could you remove the old installation in the wiki?

**Comment by winnipeg21** [comment]
> > I suggest a reinstall if need be.
> 
> Could you remove the old installation in the wiki?

What?

**Comment by xXSchrandXx** [comment]
In the readme.md and in your wiki are 2 different installation configurations.
Only the one in the readme.md is useful for the last version.
Anything you can help me to fix that error?

**Comment by winnipeg21** [comment]
Like I've said, reinstall. Delete all AB-Web files, redownload them from git or spigot (spigot being the main release) then upload the files again. Config AB to connect to your database then load your site. If your machine for your webserver is different from your MySQL server make sure your MySQL has remote access. Remote access is needed if your web server, MySQL and server are on different servers. (contact provider if need be).

**Comment by xXSchrandXx** [comment]
I deleted the web-addon, installed it with the ZIP from spigot, deleted the databasetables from AdvancedBan, set the database host, user, password and table and restarted the BungeeCord Server so they generate a new table.

And set the rights of the webfiles to 777.


Result:
```
[Tue Dec 04 18:55:57.430550 2018] [:error] [pid 898] [client *] PHP Catchable fatal error:  Argument 1 passed to AdvancedBan::initialize() must be an instance of string, string given, called in /var/www/ban/index.php on line 23 and defined in /var/www/ban/AdvancedBan/AdvancedBan.class.php on line 30
[Tue Dec 04 18:55:57.978626 2018] [:error] [pid 969] [client *] PHP Catchable fatal error:  Argument 1 passed to AdvancedBan::initialize() must be an instance of string, string given, called in /var/www/ban/index.php on line 23 and defined in /var/www/ban/AdvancedBan/AdvancedBan.class.php on line 30
```

**Comment by winnipeg21** [comment]
Are you using PHP 7.1 (recommended)?

**Comment by xXSchrandXx** [comment]
7.2.12

**Comment by winnipeg21** [comment]
use the spigot Ver

On Dec 4, 2018 2:11 PM, "xXSchrandXx" <notifications@github.com> wrote:

7.2.12

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mathhulk/advancedban-panel/issues/55#issuecomment-444200386>,
or mute the thread

**Comment by xXSchrandXx** [comment]
?

**Comment by winnipeg21** [comment]
Sorry, sent that as an email. Hmm must be an issue with the panel.

**Comment by winnipeg21** [comment]
Update your php to the latest version

**Comment by xXSchrandXx** [comment]
I am currently on the last save build, or don't it does update with sudo apt-get update?

**Comment by xXSchrandXx** [comment]
[PHPInfo](ban.ragebears.de/php.php)

**Comment by xXSchrandXx** [comment]
well, php -v does say I have 7.2.12 and phpinfo() does say I have 5.6.38-0...
fk me

**Comment by xXSchrandXx** [comment]
my bad, php7 now endabled

``` BASH
$ sudo a2dismod php5
Module php5 disabled.
To activate the new configuration, you need to run:
  service apache2 restart
$ sudo a2enmod php7.2
Considering dependency mpm_prefork for php7.2:
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled
Considering conflict php5 for php7.2:
Enabling module php7.2.
To activate the new configuration, you need to run:
  service apache2 restart
$ sudo service apache2 restart
```
Solved it...

**Comment by winnipeg21** [comment]
Is it all working?
