### ISSUE TITLE
Setting This Up On HostGator

### ISSUE THREAD

**Issue by MechaRy** [mathhulk/advancedban-panel#58]
Does anyone know how to set this up on a HostGator shared server?

**Comment by winnipeg21** [comment]
Hey! 

 To setup AB-Web all you need is to locate your html folder (this has many names) and paste in the AB-Web files. After that config your database.php file and your all set!

**Comment by winnipeg21** [comment]
Is it in your public_html or main web folder?

What is your site for your panel?
And can you show me more of your folder tree?

**Comment by MechaRy** [comment]
It is the public_html fold
![capture](https://user-images.githubusercontent.com/46309858/50598941-ff5eb180-0e71-11e9-8bb0-764633893847.PNG)
er. My panel is enderplex.xyz.

**Comment by MechaRy** [comment]
This is what happens when you go to enderplex.xyz. Catchable fatal error: Argument 1 passed to AdvancedBan::initialize() must be an instance of string, string given, called in /home2/mechary/public_html/index.php on line 23 and defined in /home2/mechary/public_html/AdvancedBan/AdvancedBan.class.php on line 30

**Comment by mathhulk** [comment]
@MechaRy, you would have to ask your host about updating.

**Comment by MechaRy** [comment]
So what version do I need to update to?

**Comment by mathhulk** [comment]
@MechaRy, the latest stable version of PHP 7 would be recommended.

**Comment by MechaRy** [comment]
The latest they have available is 7.1; will that work?

**Comment by james090500** [comment]
Yes, php7.1 should work fine
